<a href="https://colab.research.google.com/github/nihasharma-1997/class-exer/blob/main/%22assign1_YOURSTUDENT_ipynb_%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


# Task a: Generate a two-dimensional integer array with random values
data = np.random.randint(-100, 101, size=(20, 5))
data



array([[-28,  61, -40,  29,  95],
       [-57,  42, -47,   4, -72],
       [-54, -58, -10, -59, -76],
       [-93,  38,   1, -55,  71],
       [-85,  43,  86,  47, -23],
       [ 88,  51,  80,  66,  -1],
       [-94, -66, -91,  10, -53],
       [-15, -10,  73,  -6, -86],
       [-10, -86, -18,  12,   4],
       [ 67, -19,  78, -49,  29],
       [-88,  77, -46,  34, -98],
       [ 88,  55,  54,   1, -39],
       [ 54,  50, -79, -39, -31],
       [-99, -15,  40,  47, -73],
       [-45, -53, -35, -26, -53],
       [ 64,  54,  46,  20, -61],
       [-22, -10,  71, -94, -18],
       [ -6, -82, -72,  80, -85],
       [ 92,  92,  -7, -15, -89],
       [ 83,  33,  62, -56,  52]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Task b: Display the average value of the third column in "data"
average_third_column = np.mean(data[:, 2])
average_third_column


-20.85

In [ ]:
# Task c: Display the average value of the first 5 rows in "data"
average_first_five_rows = np.mean(data[:5, :])
average_first_five_rows


13.4

In [ ]:
# Task d: Display the average value of the first 3 rows and the 4th column in "data"
average_specific_rows_and_column = np.mean(data[:3, 3])
average_specific_rows_and_column


12.666666666666666

In [ ]:
# Task e: Create a new NumPy array containing the last 4 elements of the second row of "data"
new_array = data[1, -4:]
new_array


array([-39, -87,  51,  98])

In [ ]:
# Task f: Reshape "data" into a 10 x 10 matrix
reshaped_data = np.reshape(data, (10, 10))
reshaped_data


array([[ 92,  50, -63, -13,   6,  84, -39, -87,  51,  98],
       [ 30,  -2, -20,   0,  53,  27, -34, -19,  32, -20],
       [ 51,   4,  11, -30,  73,  99, 100, -69, -86,  67],
       [ 80, -23, -94, -70,   3, -94,  16, -48, -43, -31],
       [ 88,  41, -14,   6, -39,   3,  51,  40, -90, -50],
       [  0,  38,   4, -56,  31, -83, -84,  69, -84, -71],
       [ 98,  31,  81,  57, -39, -45, -21, -84,  94,  35],
       [-84,  57, -72,  62,  70, -76,  88, -95, -33,   4],
       [-45,  31,  13,   3, -26, -99, -73,  96, -53, -72],
       [-84,  23,  16,  68,  68, -91,  62, -82,  38,  99]])

In [ ]:
# Task g: Calculate the standard deviation of "data"
std_deviation = np.std(data)
std_deviation


60.549447561476555

In [ ]:
# Task h: Replace the largest number in each row with the row's average
max_indices = np.argmax(data, axis=1)
row_averages = np.mean(data, axis=1)
for i in range(len(data)):
    data[i, max_indices[i]] = row_averages[i]
data


array([[ 14,  50, -63, -13,   6],
       [ 84, -39, -87,  51,  21],
       [ 30,  -2, -20,   0,  12],
       [ 27, -34, -19,  -2, -20],
       [ 51,   4,  11, -30,  21],
       [ 99,  22, -69, -86,  67],
       [-20, -23, -94, -70,   3],
       [-94, -40, -48, -43, -31],
       [ 16,  41, -14,   6, -39],
       [  3,  -9,  40, -90, -50],
       [  0,   3,   4, -56,  31],
       [-83, -84, -50, -84, -71],
       [ 45,  31,  81,  57, -39],
       [-45, -21, -84,  -4,  35],
       [-84,  57, -72,  62,   6],
       [-76, -22, -95, -33,   4],
       [-45,  -4,  13,   3, -26],
       [-99, -73, -40, -53, -72],
       [-84,  23,  16,  18,  68],
       [-91,  62, -82,  38,   5]])

In [ ]:
# Task i: Create a new NumPy array with random 2 rows from "data"
new_array_2_rows = data[np.random.choice(data.shape[0], 2, replace=False)]
new_array_2_rows


array([[-45, -21, -84,  -4,  35],
       [-83, -84, -50, -84, -71]])

In [ ]:
# Task j: Create a new NumPy array with random 3 columns from "data"
new_array_3_columns = data[:, np.random.choice(data.shape[1], 3, replace=False)]
new_array_3_columns


array([[-13,  14, -63],
       [ 51,  84, -87],
       [  0,  30, -20],
       [ -2,  27, -19],
       [-30,  51,  11],
       [-86,  99, -69],
       [-70, -20, -94],
       [-43, -94, -48],
       [  6,  16, -14],
       [-90,   3,  40],
       [-56,   0,   4],
       [-84, -83, -50],
       [ 57,  45,  81],
       [ -4, -45, -84],
       [ 62, -84, -72],
       [-33, -76, -95],
       [  3, -45,  13],
       [-53, -99, -40],
       [ 18, -84,  16],
       [ 38, -91, -82]])

In [ ]:
# Task k: Create a new NumPy array with 100 random doubles drawn from a normal distribution
random_doubles = np.random.normal(size=100)
random_doubles


array([ 0.47908766, -0.58719658,  0.66800679, -0.48350951,  2.06509808,
       -1.73984571,  0.78901296, -0.57617658,  0.12638339,  0.83963211,
       -1.16584567,  0.94226123, -2.03241736, -0.71375643,  0.39026873,
       -0.20065765, -1.13366007,  1.04606335, -0.62109936, -0.24063623,
       -0.05699441, -1.75388498, -0.81897229, -2.69003114, -0.21906771,
       -0.74839551, -0.15389182,  1.84565802,  1.04831858, -0.48495429,
       -0.89553336, -0.00346855, -0.38156406, -1.31669617,  1.08128392,
       -2.1157266 ,  0.97507584, -1.26251899, -0.35146648, -0.58506613,
        0.37349158,  0.61720002, -0.38908739,  1.21164118,  0.83030144,
        0.90670458,  0.11569696, -0.44707685,  2.01461511,  1.04837743,
       -0.19681053,  0.58544708,  1.18155313, -1.21445751,  0.58447827,
        0.26786115,  0.81599425,  1.67782983,  0.34897548,  0.21632174,
        0.44909801, -0.24658494, -0.66994584, -0.32712264, -0.89255299,
        0.84464787,  1.86809024, -0.57079195, -1.03338633,  1.40

In [ ]:
# Task l: Convert "data" to a Pandas DataFrame with headers "a" to "e"
dataframe = pd.DataFrame(data, columns=['a', 'b', 'c', 'd', 'e'])
dataframe.describe()


a          b          c          d          e
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean  -17.600000  -2.900000 -33.600000 -16.450000  -3.450000
std    63.046683  40.601919  49.539352  47.858866  39.744546
min   -99.000000 -84.000000 -95.000000 -90.000000 -72.000000
25%   -83.250000 -25.750000 -74.500000 -53.750000 -33.000000
50%   -10.000000  -3.000000 -44.000000  -8.500000   4.500000
75%    27.750000  25.000000   5.750000   9.000000  21.000000
max    99.000000  62.000000  81.000000  62.000000  68.000000

In [ ]:
# Save the "dataframe" into assign1.xlsx and assign1.csv in /content/
dataframe.to_excel('/content/assign1.xlsx', index=False)
dataframe.to_csv('/content/assign1.csv', index=False)


In [ ]:
from google.colab import files

# Create download links for the files
files.download('/content/assign1.xlsx')
files.download('/content/assign1.csv')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# Save the "dataframe" into assign1.xlsx
dataframe.to_excel('/content/assign1.xlsx', index=False)


In [ ]:
# Save the "dataframe" into assign1.csv
dataframe.to_csv('/content/assign1.csv', index=False)


In [ ]:
# Task o: Replace negative numbers in "dataframe" with 0
dataframe[dataframe < 0] = 0
dataframe.describe()


a          b          c          d          e
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean   18.450000  14.650000   8.250000  11.750000  13.950000
std    29.704643  21.740757  19.684017  21.454665  21.219343
min     0.000000   0.000000   0.000000   0.000000   0.000000
25%     0.000000   0.000000   0.000000   0.000000   0.000000
50%     0.000000   0.000000   0.000000   0.000000   4.500000
75%    27.750000  25.000000   5.750000   9.000000  21.000000
max    99.000000  62.000000  81.000000  62.000000  68.000000

In [ ]:
# Task p: Replace zeros in "dataframe" with 1
dataframe[dataframe == 0] = 1
dataframe.describe()


a          b          c          d          e
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean   19.000000  15.200000   8.950000  12.400000  14.350000
std    29.347285  21.353171  19.378433  21.082295  20.946737
min     1.000000   1.000000   1.000000   1.000000   1.000000
25%     1.000000   1.000000   1.000000   1.000000   1.000000
50%     1.000000   1.000000   1.000000   1.000000   4.500000
75%    27.750000  25.000000   5.750000   9.000000  21.000000
max    99.000000  62.000000  81.000000  62.000000  68.000000